name: FFA
version: '1.0-SNAPSHOT'
main: me.hi.ffa.FFA
api-version: '1.20'
commands:
  break:
    description: allows to break in FFA
  savekit:
    description: allows to save a custom kit
  kits:
    description: select kit
  editkits:
    description: add and remove kits
  toggleWeatherControl:
    description: toggle control of weather
  unlockkit:
    description: unlocks kit for player
